FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl ca-certificates curl wget git sudo && rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/eoscochain/eoscochain.cdt

WORKDIR eoscochain.cdt

RUN ./build.sh

RUN cd build/packages && chmod +x generate_package.sh && ./generate_package.sh deb

# Install CDT from deb package
RUN for filename in $(ls build/packages/*.deb); do /usr/bin/dpkg -i "$filename" && rm -f "$filename"; done

WORKDIR /

USER root
