FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl ca-certificates curl wget git sudo

RUN git clone --recursive https://github.com/eoscochain/eoscochain.cdt

WORKDIR eoscochain.cdt

RUN ./build.sh

RUN ./build/packages/generate_package.sh deb

# Install CDT from deb package
ADD build/packages/*.deb /
RUN for filename in $(ls *.deb); do /usr/bin/dpkg -i "$filename" && rm -f "$filename"; done
